### ISSUE TITLE
CDC Paphos Meet & Greet August 2023

### ISSUE THREAD

**Issue by alexandra-mara** [cyprus-developer-community/events#67]
### Event Description
![изображение](https://github.com/cyprus-developer-community/events/assets/5837296/528716ea-a59a-41dc-a30f-77f642c25a3f)![image](https://media.discordapp.net/attachments/912289256154734602/1134194307042127983/IMG_4663.jpg)

Meet and greet is an informal get together to discuss the latest in technology and science, and just have a pleasant evening

Please sign up [on Eventbrite](https://www.eventbrite.ca/e/cdc-meet-greet-paphos-tickets-512982944797), so we could book tables :)

### Location
Baracas Lounge, Chloraka, Paphos https://goo.gl/maps/nwNByfDeq2JNgyvQA

### Date
24.08.2023

### Time
19.00

### Duration
2h00m

### Code of Conduct
- [x] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct.org)

### Tasks
- [x] Create a GitHub event :)
- [x] Create a Discord event or edit the one created by [gitevents bot](https://github.com/gitevents/discord-bot), if needed
- [x] Post an announcement on Discord
- [ ] Post a reminder 3–4 days prior to the event
- [ ] Book a table about 2 days before the event
